[workspace]
members = [
	"bin/substrate",
	"bin/substrate-node",
	"blockchain-service",
	"ethereum-service",
	"http-service",
	"key-server",
	"primitives",
	"substrate-service",
	"substrate-runtime/runtime",
]
